 timeunit 1ns;
 timeprecision 1ps;
 
 import DORITO_PKG::*;
 
 module DORITO_FSM
 (input  logic SYS_CLOCK,
 input  logic FSM_ARESET,
 input  logic [BUS_SIZE-1 : 0] IR_OUT,
 input  logic CARRYOUT, U_OVF, S_OVF, ALU_OUT_ZERO, ALU_OUT_POS, ALU_OUT_NEG,
 
 output  logic SCLR_PC, INC_PC, LOAD_PC,
 output  logic LOAD_IR,
 output  logic [REG_ADDR_SIZE-1 : 0] SEL_SOURCE_REG1, SEL_SOURCE_REG2, SEL_DEST_REG,
 output  logic REG_FILE_ARESET, LOAD_DEST_REG,
 output  logic LOAD_ACCUM_REG,
 output  logic IMM_OFFSET_SELECTOR,
 output  logic SEL_SOURCE1, SEL_SOURCE2,
 output  logic [MNEMONIC_SIZE-1 : 0] ALU_CONTROL,
 output  logic SEL_DATA,
 output  logic SEL_ADDR, LOAD_ADDR_REG,
 output  logic MEM_ARESET, MEM_WRITE,
 output  logic EN        //ADDED
  );
 
 logic[3:0] INSTR_TYPE;
 logic[4:0] MNEMONIC;
 logic[2:0] RD_RS_MRI;
 logic[2:0] RS1_RB_MRI;
 logic[2:0] RS2_RI_MRI_RC_BRN;
 logic[1:0] CC_BRN;
 
 assign INSTR_TYPE = IR_OUT[31:28];
 assign MNEMONIC = IR_OUT[27:23];
 assign RD_RS_MRI = IR_OUT[22:20];
 assign RS1_RB_MRI = IR_OUT[19:17];
 assign RS2_RI_MRI_RC_BRN = IR_OUT[16:14];
 assign CC_BRN = IR_OUT[13:12];
 
 logic [STATE_REG_WIDTH-1 : 0] P_STATE, N_STATE;

 always_comb
 begin : FSM_NEXT_STATE_AND_OUTPUT_LOGIC
 N_STATE = 'x;
 
 case (P_STATE)
 INIT /* 3'b000*/ :  N_STATE = FETCH;
 
 FETCH /* 3'b001*/ :  N_STATE = EXEC_RG_IM_ADDR;
 
 EXEC_RG_IM_ADDR /* 3'b010*/ :
 
 case (INSTR_TYPE) //IR_OUT[31:28]     
 REG_REG /* 4'b0000*/ : N_STATE = FETCH;
 
 REG_IMM  /* 4'b0001*/ : N_STATE = FETCH;
 
 MRI_LOAD  /* 4'b0010*/ : N_STATE = EXEC_MRI_LOAD;
 
 MRI_STORE  /* 4'b0011*/ : N_STATE = EXEC_MRI_STORE;
 
 BRANCH   /* 4'b0100*/ :
 
 if ((CC_BRN == 2'b00 && ALU_OUT_ZERO) || //BRANCH IF RC = 0
 (CC_BRN == 2'b01 && ALU_OUT_POS)  || //BRANCH IF RC IS +VE
 (CC_BRN == 2'b10 && ALU_OUT_NEG)  || //BRANCH IF RC IS -VE
 (CC_BRN == 2'b11) )     //BRANCH ALWAYS//
 N_STATE = EXEC_BRANCH;
 else N_STATE = FETCH;
 default : N_STATE = FETCH;
 endcase
 
EXEC_MRI_LOAD /* 3'b011*/ : N_STATE = FETCH;
EXEC_MRI_STORE /* 3'b100*/ : N_STATE = FETCH;
EXEC_BRANCH  /*3'b101*/ : N_STATE = FETCH;
default : N_STATE = INIT;
endcase

SEL_SOURCE1 = '1; SEL_SOURCE2 = '0; SEL_DATA = '0; SEL_ADDR = '0;      
IMM_OFFSET_SELECTOR = '0;
SCLR_PC = '0; INC_PC = '0; LOAD_PC = '0; REG_FILE_ARESET = '0;
LOAD_IR = '0; LOAD_ADDR_REG = '0; LOAD_DEST_REG = '0; LOAD_ACCUM_REG = '0;
SEL_SOURCE_REG1 = '0; SEL_SOURCE_REG2 = '0; SEL_DEST_REG = '0;
ALU_CONTROL = '0;
MEM_WRITE = '0;
MEM_ARESET = '0;
EN = '0; //ADDED

case (P_STATE)
INIT /* 3'b000*/  :  begin
SCLR_PC = '1;
REG_FILE_ARESET = '1;
MEM_ARESET = '1;
end
FETCH /* 3'b001*/  :  begin
INC_PC = '1;
//SEL_ADDR = '0; //PASS PC_OUT TO MEM_ADDRESS
//SEL_DATA = '0; //PASS MEM_DATA_OUT TO INT_DATA_BUS
LOAD_IR = '1;

//ADDED
         if (INSTR_TYPE==4'b0011)
                 MEM_WRITE = '1;
 end
 EXEC_RG_IM_ADDR /* 3'b010*/  :                   
  case (INSTR_TYPE) //IR_OUT[31:28]

 REG_REG /* 4'b0000*/  : begin
  SEL_SOURCE_REG1 = RS1_RB_MRI; //IR_OUT[19:17];
   //SEL_SOURCE1 = '1;     //PASS SOURCE_REG1 TO ALU_IN1
      SEL_SOURCE_REG2 = RS2_RI_MRI_RC_BRN; //IR_OUT[16:14];
     //SEL_SOURCE2 = '0; //PASS SOURCE_REG2 TO ALU_IN2

  ALU_CONTROL = MNEMONIC; //IR_OUT[27:23];
     SEL_DATA = '1; //PASS ALU_OUT   TO INT_DATA_BUS
     SEL_DEST_REG =  RD_RS_MRI; //IR_OUT[22:20];
     LOAD_DEST_REG = '1;
      LOAD_ACCUM_REG = '1; //ADDED
     end

      REG_IMM /* 4'b0001*/  : begin
     SEL_SOURCE_REG1 = RS1_RB_MRI; //IR_OUT[19:17];
     //SEL_SOURCE1 = '1; //PASS SOURCE_REG1 TO ALU_IN1
     IMM_OFFSET_SELECTOR = '1;  //change
     //MAKE IMMEDIATE DATA 32BITS AND PASS IT TO MUX2
      SEL_SOURCE2 = '1;
       
       ALU_CONTROL = MNEMONIC; //IR_OUT[27:23];
      SEL_DATA = '1; //PASS ALU_OUT TO INT_DATA_BUS
     SEL_DEST_REG =  RD_RS_MRI; //IR_OUT[22:20];
     LOAD_DEST_REG = '1;
      LOAD_ACCUM_REG = '1; //ADDED
     end

     MRI_LOAD /* 4'b0010*/  : begin
     SEL_SOURCE_REG1 = RS1_RB_MRI; //IR_OUT[19:17];
     //SEL_SOURCE1 = '1; //PASS SOURCE_REG1 TO ALU_IN1

      SEL_SOURCE_REG2 = RS2_RI_MRI_RC_BRN;  //IR_OUT[16:14];
      //SEL_SOURCE2 = '0; //PASS SOURCE_REG2 TO ALU_IN2

     ALU_CONTROL = ADD; //'0;//ADD (ADDING BASE AND INDEX ADDRESS)
      LOAD_ADDR_REG = '1;
      LOAD_ACCUM_REG = '1; //ADDED
     end

      MRI_STORE /* 4'b0011*/  : begin
     SEL_SOURCE_REG1 = RS1_RB_MRI; //IR_OUT[19:17];
     //SEL_SOURCE1 = '1; //PASS SOURCE_REG1 TO ALU_IN1

      SEL_SOURCE_REG2 = RS2_RI_MRI_RC_BRN; //IR_OUT[16:14];
     //SEL_SOURCE2 = '0; //PASS SOURCE_REG2 TO ALU_IN2

    ALU_CONTROL = ADD; //'0; //ADD (ADDING BASE AND INDEX ADDRESS)
     LOAD_ADDR_REG = '1;
      LOAD_ACCUM_REG = '1; //ADDED
     MEM_WRITE = '1; //ADDED FOR TEST
    //SEL_ADDR = '1; //ADDED FOR TEST
     end

    BRANCH   /* 4'b0100*/ : begin    
    SEL_SOURCE_REG2 = RS2_RI_MRI_RC_BRN;  //IR_OUT[16:14];
    ALU_CONTROL = PASS_IN2; //5'b00101; //PASS ALU_IN2 TO ALU_OUT
    end
    default : ;
    endcase

    EXEC_MRI_LOAD /* 3'b011*/  : begin
   SEL_ADDR = '1; //PASS ADDR_REG_OUT TO MEM_ADDRESS
   EN = '1; //ADDED
     
  SEL_DEST_REG =  RD_RS_MRI;
  LOAD_DEST_REG = '1; //IR_OUT[22:20];
 LOAD_ACCUM_REG = '1; //ADDED
  end

 EXEC_MRI_STORE /* 3'b100*/  : begin
 
 SEL_SOURCE_REG2 = RD_RS_MRI;//CHANGED
 ALU_CONTROL = PASS_IN2;//5'b00101; //PASS ALU_IN2 TO MEM_DATA_IN
 EN = '1; //ADDED
 LOAD_ACCUM_REG = '1; //ADDED

 SEL_ADDR = '1; //PASS ADDR_REG_OUT TO MEM_ADDRESS 
 MEM_WRITE = '1; //WRITE TO MEMORY
 end

 EXEC_BRANCH /*3'b101*/ :        begin
 SEL_SOURCE1 = '0; //PASS PC_OUT TO ALU_IN1
IMM_OFFSET_SELECTOR = '1; //CHANGE

 SEL_SOURCE2 = '1; //PASS OFFSET TO ALU_IN2

 ALU_CONTROL = ADD;//ADD; //ADD (ADD OFFSET TO PC)
 LOAD_ACCUM_REG = '1; //ADDED
 SEL_DATA = '1; //PASS ALU_OUT   TO INT_DATA_BUS
 LOAD_PC = '1;  //CHANGE PC AS REQUIRE BY BRANCH INSTRUCTIONS
 end

default : ;
 endcase
 end : FSM_NEXT_STATE_AND_OUTPUT_LOGIC

always_ff @ (posedge SYS_CLOCK, posedge FSM_ARESET)
begin : FSM_PRESENT_STATE_REG

if (FSM_ARESET)
P_STATE <= '0;
 else
 P_STATE <= N_STATE;
 end : FSM_PRESENT_STATE_REG
 endmodule : DORITO_FSM  
