 timeunit 1ns;
 23 timeprecision 1ps;
 24
 25 import DORITO_PKG::*;
 26
 27 module DORITO_SYSTEM_TOP_tb;
 28 //`include "DORITO_PKG.v"
 29 //Internal signals declarations:
 30 logic SYS_CLOCK;
 31 logic FSM_ARESET;
 32
 33 //NET/VARIABLE DECLARATIONS FOR SIGNALS REFERRED TO HIERARCHICALLY (FROM LOWER LEVEL moduleS)
 34  logic [STATE_REG_WIDTH-1 : 0] P_STATE, N_STATE;
 35  logic MEM_ARESET,MEM_WRITE;
 36  logic EN; //ADDED
 37 //var logic [BUS_SIZE-1 : 0]  MEM_DATA_IN;
 38 wire [BUS_SIZE-1 : 0]  MEM_DATA_IN;  //CHANGE
 39 //var logic [BUS_SIZE-1 : 0] MEM_ARRAY_UPTO_31 [BUS_SIZE-1 : 0]; //FIRST 32 BITS OUT OF 2^32 MEMORY CONTENTS
 40  logic [BUS_SIZE-1 : 0] MEM_ARRAY [ADDRESS_HEIGHT-1 : 0];
 41
 42  logic SCLR_PC, INC_PC, LOAD_PC;
 43  logic [4 : 0] PC_OUT; //MAKE PC_OUT 5 BIT (CAN POINT TO 32 LOCATIONS) FOR EASIER VERIFICATION.
 44 /*var logic [BUS_SIZE-1 : 0] PC_OUT;*/
 45  logic SEL_ADDR,LOAD_ADDR_REG;
 46  logic [4 : 0] ADDR_REG_OUT; //MAKE ADDR_REG_OUT 5 BIT (CAN POINT TO 32 LOCATIONS) FOR EASIER VERIFICATION.
 47 /*var logic [BUS_SIZE-1 : 0] ADDR_REG_OUT;*/
 48  logic [4 : 0] MEM_ADDRESS; //MAKE ADDRESS 5 BIT (CAN POINT TO 32 LOCATIONS) FOR EASIER VERIFICATION.
 49 /*var logic [BUS_SIZE-1 : 0]  MEM_ADDRESS;*/
 50  logic [BUS_SIZE-1 : 0]  MEM_DATA_OUT;
  52  logic LOAD_IR;
 53  logic [BUS_SIZE-1 : 0] IR_OUT;
 54
 55  logic [BUS_SIZE-1 : 0] IMM_OFFSET_DATA;
 56
 57  logic [REG_ADDR_SIZE-1 : 0] SEL_SOURCE_REG1, SEL_SOURCE_REG2;
 58  logic IMM_OFFSET_SELECTOR, SEL_SOURCE1, SEL_SOURCE2;
 59  logic [BUS_SIZE-1 : 0] SOURCE_REG1, SOURCE_REG2;
 60  logic [BUS_SIZE-1 : 0] ALU_IN1, ALU_IN2;
 61
 62  logic [MNEMONIC_SIZE-1 : 0] ALU_CONTROL;
 63  logic [BUS_SIZE : 0] ALU_OUT_W_CARRY;
 64  logic [BUS_SIZE-1 : 0] ALU_OUT;
 65  logic CARRYOUT, U_OVF, S_OVF, ALU_OUT_ZERO, ALU_OUT_POS, ALU_OUT_NEG;
 66
 67  logic [BUS_SIZE-1 : 0] INT_DATA_BUS;
 68  logic SEL_DATA;
 69  logic [REG_ADDR_SIZE-1 : 0]    SEL_DEST_REG;
 70  logic REG_FILE_ARESET, LOAD_DEST_REG;
 71  logic [BUS_SIZE-1 : 0] R_FILE [REGISTER_NO-1 : 0];
 72  logic LOAD_ACCUM_REG;
 73  logic [BUS_SIZE-1 : 0] ACCUM_REG;
 74
 75 //HIERARCHICAL REFERENCING (RETRIEVING NETS/VARIABLES FROM LOWER LEVEL MODULES
 76 //AND ASSIGNING THEM TO NETS/VARIABLES OF AN UPPER LEVEL MODULE FOR EASIER
 77 //VIEWING IN SIMULATION)
 78
 79 //RETRIEVING INTERNAL SIGNALS FROM DORITO_SYSTEM_TOP (INSTANTIATED AS UUT)
 80 //assign MEM_DATA_OUT = DORITO_SYSTEM_TOP_tb.UUT.MEM_DATA_OUT;
 81 //assign MEM_ADDRESS = DORITO_SYSTEM_TOP_tb.UUT.MEM_ADDRESS;  
 82 //assign MEM_DATA_IN = DORITO_SYSTEM_TOP_tb.UUT.MEM_DATA_IN;
 83 //assign MEM_ARESET = DORITO_SYSTEM_TOP_tb.UUT.MEM_ARESET;
 84 //assign MEM_WRITE = DORITO_SYSTEM_TOP_tb.UUT.MEM_WRITE;
 85
 86 //RETRIEVING INTERNAL SIGNALS FROM DORITO_PROCESSOR_TOP (INSTANTIATED AS PROC_TOP)
 87 assign SCLR_PC = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SCLR_PC;
 88 assign LOAD_PC = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.LOAD_PC;
 89 assign INC_PC = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.INC_PC;
 90 assign LOAD_IR = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.LOAD_IR;
 91 assign REG_FILE_ARESET = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.REG_FILE_ARESET;
 92 assign LOAD_DEST_REG = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.LOAD_DEST_REG;
 93 assign IMM_OFFSET_SELECTOR = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.IMM_OFFSET_SELECTOR;
 94 assign SEL_SOURCE1 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_SOURCE1;
 95 assign SEL_SOURCE2 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_SOURCE2;
 96 assign SEL_DATA = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_DATA;
 97 assign SEL_ADDR = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_ADDR;
 98 assign LOAD_ADDR_REG = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.LOAD_ADDR_REG;
 99 assign CARRYOUT = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.CARRYOUT;
100 assign U_OVF = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.U_OVF;
101 assign S_OVF = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.S_OVF;
102 assign ALU_OUT_ZERO = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.ALU_OUT_ZERO;
103 assign ALU_OUT_POS = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.ALU_OUT_POS;
104 assign ALU_OUT_NEG = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.ALU_OUT_NEG;
105 assign ALU_CONTROL = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.ALU_CONTROL;
106 assign IR_OUT = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.IR_OUT;
107 assign SEL_SOURCE_REG1 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_SOURCE_REG1;
108 assign SEL_SOURCE_REG2 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_SOURCE_REG2;
109 assign SEL_DEST_REG = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.SEL_DEST_REG;
110 assign LOAD_ACCUM_REG = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.LOAD_ACCUM_REG;
111 assign EN = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.EN;                          
113 //RETRIEVING INTERNAL SIGNALS FROM DORITO_MEMORY (INSTANTIATED AS MEM)
114 //assign MEM_ARRAY_UPTO_31 = DORITO_SYSTEM_TOP_tb.UUT.MEM.MEM_ARRAY[BUS_SIZE-1 : 0];
115 assign MEM_ARRAY = DORITO_SYSTEM_TOP_tb.UUT.MEM.MEM_ARRAY;
116
117 //RETRIEVING INTERNAL SIGNALS FROM DORITO_DATAPATH (INSTANTIATED AS DP)
118 assign INT_DATA_BUS = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.INT_DATA_BUS;
119 assign IMM_OFFSET_DATA = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.IMM_OFFSET_DATA;
120 assign SOURCE_REG1 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.SOURCE_REG1;
121 assign SOURCE_REG2 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.SOURCE_REG2;
122 //assign PC_OUT = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.PC_OUT;
123 assign ADDR_REG_OUT = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.ADDR_REG_OUT;
124 assign ALU_IN1 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.ALU_IN1;
125 assign ALU_IN2 = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.ALU_IN2;
126 assign ALU_OUT = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.ALU_OUT;
127 assign ALU_OUT_W_CARRY = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.ALU_OUT_W_CARRY;
128 assign R_FILE = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.DP.R_FILE;
129
130
131
132 //RETRIEVING INTERNAL SIGNALS FROM DORITO_FSM (INSTANTIATED AS FSM)
133 assign P_STATE = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.FSM.P_STATE;
134 assign N_STATE = DORITO_SYSTEM_TOP_tb.UUT.PROC_TOP.FSM.N_STATE;
135
136 // Unit Under Test port map
137 DORITO_SYSTEM_TOP UUT (
138 .SYS_CLOCK(SYS_CLOCK),
139 .FSM_ARESET(FSM_ARESET),
140 .MEM_DATA_OUT(MEM_DATA_OUT),
141 .PC_OUT(PC_OUT),
142 .MEM_ADDRESS(MEM_ADDRESS),    
143 .MEM_ARESET(MEM_ARESET),
144 .MEM_WRITE(MEM_WRITE),
145 .MEM_DATA_IN(MEM_DATA_IN),
146 .ACCUM_REG(ACCUM_REG)
147 );
148
149
150 const time CLOCK_PERIOD = 100ns;
151
152 initial
153 begin
154 FSM_ARESET <= '0;
155 SYS_CLOCK <= '0;
156
157 forever
158 begin
159 #(CLOCK_PERIOD/2) SYS_CLOCK <= ~ SYS_CLOCK;
160 end
161
162 end
163
164
165 const time RUN_TIME = 4500;
166 initial
167 begin
168 #RUN_TIME $finish;
169
170 end
171
172 endmodule : DORITO_SYSTEM_TOP_tb   

